---

name: 'JudCoCo'
description: 'Judge of Conventional Commit - Write better commit description 🥤🥥'
inputs:
  base:
    description: "Base branch"
    default: "master"
    required: true
  head:
    description: "HEAD to check diff"
    required: true
runs:
  using: 'docker'
  image: 'docker://meilleursagentstech/judcoco:latest'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.head }}
